version: "3.9"
services:
  ubuntu1:
    container_name: my-ubuntu
    build:
      context: .
      dockerfile: ubuntu/Dockerfile
    networks:
      # if you put this network here, then the inner ports are exposed to all the other container that joined the same network
      - common
    #extra_hosts: # I *think* that this is how you add contents to the /etc/hosts file
    #  - "<hostname>:<ip>"

  ubuntu2:
    build:
      context: .
      dockerfile: ubuntu/Dockerfile
    networks:
      # if you put this network here, then the inner ports are exposed to all the other container that joined same network
      - common

  root-fedora:
    extends:
      file: sub-project/docker-compose.yml
      service: fedora
    container_name: extended-fedora
    build:
      context: ./sub-project
    depends_on:
      # services with `depends_on` cannot be extended, however you can use it in the extension itself 
      - nginx

  nginx:
    build:
      context: nginx
    ports:
      - "9999:80" # if you uncomment this line then the 9876 port is available to the host OS
    networks:
      - common

networks:
  # https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge
  common:
    external: true
