version: "3.9"
services:
  httpbin:
    container_name: simple-httpbin
    image: kennethreitz/httpbin
    #ports:
    #  - "9876:80" # if you speficy only this line: the host port is available to the host OS
    networks:
      # if you put this network here, then the inner ports are exposed to all the other container that joined same network
      - playground

  ubuntu:
    container_name: my-ubuntu
    build:
      context: .
      dockerfile: ubuntu/Dockerfile
    networks:
      # if you put this network here, then the inner ports are exposed to all the other container that joined same network
      - playground

networks:
  playground:
    driver: bridge
