version: "3.9"
services:
  fedora:
    container_name: fedora
    depends_on:
      - nginx
    build:
      context: .
      dockerfile: sub-project/fedora/Dockerfile
    networks:
      - common

networks:
  # https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge
  common:
    external: true
