FROM ubuntu:latest

RUN apt -y update
RUN apt -y install curl
RUN apt -y install vim
RUN apt -y install tmux
RUN apt -y install iputils-ping
RUN apt -y install iproute2

ENTRYPOINT [ "sleep", "infinity" ]